
language: python
python:
  - "3.4.2"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - echo "no scripts"

after_success:
  - bash <(curl -s -s https://scripts.scantist.com/ci-travis.sh)
  #- bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)
